import { urlFinalPaper } from '../../constants/Constants';
import $t from '../../translation/Translation';
import technologies from '../Technology/Technologies';
import Project from './Project';

const t = technologies;

const projects: Array<Project> = [
  new Project(
    $t('cultueTitle'),
    $t('cultueSubtitle'),
    [
      t.Javascript,
      t.HTML5,
      t.CSS3,
      t.Redux,
      t.Firebase,
      t.ReactJs,
      t.ReactRouter,
      t.Sendgrid,
      t.APIRest,
    ],
    $t('cultueDescription'),
    'https://cultue.web.app/',
    'projects/Cultue.svg',
    'https://github.com/ThiagoMaia1/cultue-slides',
    [
      // 'Cultue/Front Topo.png',
      // 'Cultue/Front Bottom.png',
      // 'Cultue/Login.png',
      'Cultue/Main.png',
      // 'Cultue/Música.png',
      // 'Cultue/Fundos.png',
      // 'Cultue/Select Filtro.png',
      // 'Cultue/Exportar.png',
      // 'Cultue/Atalhos.png',
      // 'Cultue/Imagens Usuário.png',
      // 'Cultue/Perfil.png',
      // 'Cultue/Lista de Apresentações.png',
    ],
    undefined,
    'https://cultue.web.app',
    22
  ),
  new Project(
    $t('bibleForHumansTitle'),
    $t('bibleForHumansSubtitle'),
    [
      t.APIRest,
      t.NodeJs,
      t.Express,
      t.Vue,
      t.VueI18n,
      t.Typescript,
      t.HTML5,
      t.SASS,
      t.AWS,
      t.Firebase,
      // t.Sendgrid,
    ],
    $t('bibleForHumansDescription'),
    'https://bibliaparahumanos.web.app/home',
    'projects/BibliaParaHumanos.svg',
    'https://github.com/ThiagoMaia1/api-biblia',
    [
      'BibliaParaHumanos/Home.png',
      // 'BibliaParaHumanos/TryOut.png',
      // 'BibliaParaHumanos/Examples.png',
      // 'BibliaParaHumanos/Footer.png',
      // 'BibliaParaHumanos/Documentation.png',
      // 'BibliaParaHumanos/Help1.png',
      // 'BibliaParaHumanos/Help2.png',
    ],
    {
      url: 'https://github.com/ThiagoMaia1/pagina-api-biblia', 
      label: $t('bibleForHumansLink'),
    },
    'https://bibliaparahumanos.web.app/home',
  ),
  new Project(
    $t('myShopTitle'),
    $t('myShopSubtitle'),
    [t.Dart, t.Flutter, t.Figma, t.Trello,],
    $t('myShopDescription'),
    'https://youtu.be/BJljtECxGkE',
    'projects/MyShop.png',
    'https://github.com/ThiagoRavier/ecommerce',
    [
      'MyShop/Registration.png',
      'MyShop/Home.png',
      'MyShop/Catalogue.png',
      'MyShop/Gallery.png',
      'MyShop/Product.png',
      'MyShop/Cart.png',
      'MyShop/Closing.png',
      'MyShop/Profile.png',
    ],
    {
      url: 'https://www.figma.com/file/bHEvWMeeRywiIU9fU5T6yn/Mobile-App-FIGMA-(E-commerce-template)-by-Oleh-Chabanov', 
      label: $t('figmaBy'),
    },
    undefined,
    35
  ),
  new Project(
    $t('ballGameTitle'),
    $t('ballGameSubtitle'),
    [t.Typescript, t.HTML5, t.SASS, t.Angular, t.Firebase, t.AWS],
    $t('ballGameDescription'),
    'https://master.d2gy6xsqkmio1s.amplifyapp.com/',
    'companies/mereo.svg',
    'https://github.com/ThiagoMaia1/angular-game',
    [
      // 'BallGame/Start.png',
      'BallGame/GamePlay.png',
      'BallGame/InsertName.png',
      'BallGame/Ranking.png',
    ],
    undefined,
    'https://www.mereobounce.tk/'
  ),
  new Project(
    $t('vidAngelTitle'),
    $t('vidAngelSubtitle'),
    [
      t.Javascript,
      t.HTML5,
      t.CSS3,
      t.ChromeCast,
      t.ChromeExtensions,
      t.Postman,
      t.APIRest,
    ],
    $t('vidAngelDescription'),
    'https://chrome.google.com/webstore/detail/vidangel-subtitles/glnfgjbdffkpaphaiablhgenfoigmfbj?hl=pt-BR&authuser=0',
    'projects/VidAngelSubtitles.png',
    'https://github.com/ThiagoMaia1/vidangel-subtitles',
    [
      'VidAngelSubtitles/PrintExtensão.png',
      'VidAngelSubtitles/PrintExtensão2.png',
      'VidAngelSubtitles/PrintExtensão3.png',
    ],
    {
      url: 'https://www.vidangel.com/browse',
      label: $t('vidAngelLink'),
    },
    undefined,
    35
  ),
  new Project(
    $t('ultimatoSystemTitle'),
    $t('ultimatoSystemSubtitle'),
    [t.Access, t.Excel, t.VBA, t.SQL, t.HTML5],
    $t('ultimatoSystemDescription'),
    urlFinalPaper,
    'projects/Ultimato.png',
    '',
    [
      'Ultimato/ExpedicaoBase.png',
      'Ultimato/ExpedicaoNovo.png',
      'Ultimato/EntradaProdutos.png',
      'Ultimato/ColetaTransportadora.png',
      'Ultimato/PostagensRealizadas.png',
      'Ultimato/Presentes.png',
      'Ultimato/ReclamacoesInserir.png',
      'Ultimato/Transferencias.png',
      'Ultimato/VendasNovo.png',
    ],
    {
      url: urlFinalPaper, 
      label: $t('ultimatoFinalPaperLink'),
    }
  ),
  new Project(
    $t('boardGameHelperTitle'),
    $t('boardGameHelperSubtitle'),
    [t.Typescript, t.HTML5, t.SASS, t.ReactNative],
    $t('boardGameHelperDescription'),
    'https://youtu.be/9Owm3zBeq8Q',
    'projects/BoardGame.png',
    'https://github.com/ThiagoMaia1/board-game-helper.git',
    [
      'BoardGameHelper/CharacterSelection.png',
      'BoardGameHelper/CharacterInfo.png',
      'BoardGameHelper/MainPagePortrait.png',
      'BoardGameHelper/ChapterHistory.png',
      'BoardGameHelper/MainPageLandscape.png',
    ],
    undefined,
    undefined,
    20
  ),
  // new Project(
  //   $t('acaiAntonioTitle'),
  //   $t('acaiAntonioSubtitle'),
  //   [t.Typescript, t.HTML5, t.CSS3, t.ReactNative],
  //   $t('acaiAntonioDescription'),
  //   'https://youtu.be/BWt3QXCnMxY',
  //   'projects/AcaiAntonio.png',
  //   'https://github.com/ThiagoMaia1/acai-antonio',
  //   [
  //     'Acai/Início.png',
  //     'Acai/Tamanhos.png',
  //     'Acai/Recheios.png',
  //   ],
  // ),
  // new Project(
  //   $t('portfolioTitle'),
  //   $t('portfolioSubtitle'),
  //   [t.Typescript, t.HTML5, t.SASS, t.ReactJs, t.PaperJs, t.AWS, t.StyledComponents],
  //   $t('portfolioDescription'),
  //   window.location.origin,
  //   'projects/Portfolio.svg',
  //   'https://github.com/ThiagoMaia1/portfolio',
  //   [],
  //   undefined,
  //   window.location.origin + '/' + Date.now().toString(),
  // ),
];

export default projects;
